#!/bin/bash

dwm > /var/log/dwm/dwm.log 2> /var/log/dwm/error.log &
/opt/flux/xflux -l 51.5

xset r rate 200 120
feh --bg-fill /home/moona/Desktop/desktop.jpg
setxkbmap -layout gb
xscreensaver -no-splash &

cat > /tmp/shortcuts.txt <<EOF
alt + Q                 previous screen
alt + W                 next screen
alt + shift + Q         shift to previous screen
alt + shift + W         shift to next screen

alt + S                 next tile
alt + A                 previous tile
alt + shift + S         shift to next tile
alt + shift + A         shift to previous tile

alt + X                 fullscreen
alt + Z                 tiled (default)

alt + Left              make stack bigger
alt + Right             make stack smaller
alt + shift + Left      stack -> master
alt + shift + Right     master -> stack

alt + D                 toggle stack h/v
alt + shift + D         rotate stack
alt + ctrl + shift + D  rotate master

alt + Enter             swap to master
alt + shift + Enter     flip layout

alt + [num]             switch to tag
alt + P                 launcher

alt + C                 volume down
alt + V                 volume up

alt + F                 shortcuts (i.e. THIS!)

alt + ctrl + Enter      terminator
alt + ctrl + L          lock screen
alt + ctrl + A          control center
alt + ctrl + F          file manager
alt + ctrl + W          web browser
alt + ctrl + M          SUPER DEV KEY!
alt + ctrl + N          new super dev key...
alt + ctrl + Q          log out
EOF

xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --addmode VGA1 1920x1080_60.00
xrandr --output VGA1 --mode 1920x1080_60.00
xrandr --output LVDS1 --primary --auto --output VGA1 --right-of LVDS1 --auto

while true; do
    xsetroot -name "`date`"
    if [[ -z "$(ps -axo comm | grep dwm$)" ]]; then exit; fi
    sleep 1
done

