#!/bin/bash
xmessage -center -buttons "Got it":0,"Halt":2,"Reboot":4 -default "Got it" -file /tmp/shortcuts.txt
button=$?
if (( $button == 2 )); then sudo halt
elif (( $button == 4 )); then sudo reboot
fi
