#!/bin/bash
xmessage -center -buttons "Got it":0,"Power Off":2,"Reboot":4,"Suspend":8,"Hibernate":16 -default "Got it" -file /tmp/shortcuts.txt
button=$?
if (( $button == 2 )); then sudo poweroff
elif (( $button == 4 )); then sudo reboot
elif (( $button == 8 )); then sudo pm-suspend
elif (( $button == 16 )); then sudo pm-hibernate
fi
